language: go
sudo: false
env:
  - PATH=$PATH:$GOPATH/bin
before_install:
  - go get -u github.com/mattn/goveralls
  - curl -L 'http://sourceforge.net/projects/plantuml/files/plantuml.jar/download' > /tmp/plantuml.jar
install:
  - go get -t ./...
script:
  - $GOPATH/bin/goveralls -v -service=travis-ci
